[package]
name = "lc-rs"
version = "0.1.0"
authors = ["jRimbault <jacques.rimbault@gmail.com>"]
edition = "2018"

[dependencies]
ignore = "0.4.16"
structopt = "0.3.17"
streaming-stats = "0.2.3"
anyhow = "1.0.32"
